name: DeathBan
main: com.github.sar3th.DeathBan.DeathBan
description: Automatically bans a player after death for a configurable amount of time
version: 0.1
author: sar3th
website: https://github.com/sar3th/DeathBan

commands:
  db-ban:
    description: Bans a player for a specified amount of time
    usage: "Usage: /<command> <player> <time in seconds>"
    permission: DeathBan.BanPlayer
    permission-message: You are not allowed to ban players because you don't have <permission>.
  db-list:
    description: Lists the banned players and their remaining bantime.
    usage: "Usage: /<command> [<player>]"
    permission: DeathBan.ListBans
    permission-message: You are not allowed to see the banlist because you don't have <permission>.
  db-settime:
    description: Allows you to set the amount of time that a player is banned for after death
    usage: "Usage: /<command> <time in seconds>"
    permission: DeathBan.SetTime
    permission-message: You are not allowed to edit this value because you don't have <permission>.
  permissions:  
    DeathBan.*:
      description: Gives access to all DeathBan commands
      children:
        DeathBan.SetTime: true
        DeathBan.ListBans: true
        DeathBan.BanPlayer: true
    DeathBan.SetTime:
      default: op
      description: Allows players to set the amount of time that a player is banned for after death
    DeathBan.BanPlayer:
      default: op
      description: Allows players to trigger a DeathBan on other players.
    DeathBan.ListBans:
      default: true
      description: Allows palyers to see the list of banned players.